---
- name: Play-1 Configure NTP 
  hosts: 'localhost'
  become: yes
  tasks:
    - name: Update Ubuntu Repository
      apt: update_cache=yes
      ignore_errors: yes
      
    - name: Install NTP Server
      apt: name=ntp state=present 

    - name: Enable and Start NTP Service 
      service: name=ntp state=restarted 
...
